# === Server Configuration ===
server.port=8083
spring.application.name=rabbitmq-1


# === RabbitMQ Configuration ===
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5673
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

# === Logging Configuration ===
spring.output.ansi.enabled=always
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){cyan} %clr(%5p){yellow} %clr([%t]){magenta} %clr(%c{1}){green} - %clr(%m){black}%n
logging.level.root=INFO
logging.level.org.springframework.amqp=DEBUG
logging.level.com.yourcompany=DEBUG